### PR TITLE
Added Spanish translation

### PR DESCRIPTION
**Pull request by d4r1us-drk**

### CODE REVIEW

**Comment by ideveCore** [comment]
Hello, I will check this pull soon

**Comment by ideveCore** [comment]
Thanks for the contribution

**Comment by ideveCore** [comment]
If possible, please make a merge request for the release-1.2.0 branch

**Comment by d4r1us-drk** [comment]
Thanks for pointing that out, I'm sorry I didn't see the 1.20 branch, gonna make the merge request soon.

**Comment by d4r1us-drk** [comment]
Sorry for the inactivity, I was really busy. I didn't know how to create a merge request for a specific branch. Now that I see that realease 1.2.0 is comming along and Github actions failed, I will close this pull request and use Weblate instead.

**Comment by ideveCore** [comment]
No problem, the github actions are only for the release-1.2.0 branch, they are just tests, I'm glad you will use Weblate, Thanks for the contribution

**Pull request closed without merging**
