### PR TITLE
Several patches mostly related to translation

### PR DESCRIPTION
**Pull request by sabriunal**
Please review individually.

### CODE REVIEW

**Comment by ideveCore** [comment]
Hello, thank you for your contribution. I am reviewing it before merging, but if possible, please redo your pull request for the release-1.2.0 branch.

**Comment by ideveCore** [comment]
> Hello, thank you for your contribution. I am reviewing it before merging, but if possible, please redo your pull request for the release-1.2.0 branch.

Branch: https://github.com/ideveCore/currency-converter/tree/release-1.2.0

**Comment by sabriunal** [comment]
Updated and applied against release-1.2.0

**Comment by ideveCore** [comment]
Hello, thank you for your contribution! The merge has been completed, but the application is currently undergoing an update. Some things were removed, and others were added. Please feel free to contribute further to the application—I appreciate it!

The translations for the application will now be done through WebLate. Please visit [WebLate](https://hosted.weblate.org/projects/currency-converter/currency-converter/)
 for updates. The Turkish translation will soon be available there when the release-1.2.0 branch is merged into the main branch.

**Pull request merged**
